server.port=${SERVER_PORT:8080}

auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
group.service.url=${GROUP_SERVICE_URL:http://localhost:8082}
project.service.url=${PROJECT_SERVICE_URL:http://localhost:8083}
task.service.url=${TASK_SERVICE_URL:http://localhost:8084}
judging.service.url=${JUDGING_SERVICE_URL:http://localhost:8085}
